
name: C++ Build & Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt update && sudo apt install g++ -y

    - name: Compile code
      run: g++ -std=c++17 -o main *.cpp

    - name: Run program
      run: ./main
